libraries/libchewing: Updated for version 0.3.4_20130315git

diff --git a/libraries/libchewing/libchewing.SlackBuild b/libraries/libchewing/libchewing.SlackBuild
--- a/libraries/libchewing/libchewing.SlackBuild
+++ b/libraries/libchewing/libchewing.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for libchewing
 
-# Copyright 2010,2011  Guan-Zhong Huang, Taiwan <imprazaguy@gmail.com>
+# Copyright 2010-2013  Guan-Zhong Huang, Taiwan <imprazaguy@gmail.com>
 # All rights reserved.
 #
 # Redistribution and use of this script, with or without modification, is
@@ -23,15 +23,16 @@
 # ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 PRGNAM=libchewing
-VERSION=${VERSION:-0.3.3}
+VERSION=${VERSION:-0.3.4_20130315git}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_SBo}
+
+COMMIT_ID=fafe7074a0e78014f91557f3b2af58f4a3aacff8
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i486 ;;
     arm*) ARCH=arm ;;
-    # Unless $ARCH is already set, use uname -m for all other archs:
        *) ARCH=$( uname -m ) ;;
   esac
 fi
@@ -55,14 +56,22 @@ else
   LIBDIRSUFFIX=""
 fi
 
-set -e # Exit on most errors
+set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
-cd $PRGNAM-$VERSION
+rm -rf $PRGNAM-$COMMIT_ID
+if [ -r "$CWD/$PRGNAM-$COMMIT_ID.tar.gz" ]; then
+  tar xvf $CWD/$PRGNAM-$COMMIT_ID.tar.gz
+# Check other filename if wget is used without --content-disposition option
+elif [ -r "$CWD/$COMMIT_ID.tar.gz" ]; then
+  tar xvf $CWD/$COMMIT_ID.tar.gz
+else
+  echo "Couldn't find source of $PRGNAM"
+  exit 1
+fi
+cd $PRGNAM-$COMMIT_ID
 chown -R root:root .
 find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
@@ -70,23 +79,28 @@ find . \
  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
  -exec chmod 644 {} \;
 
+./autogen.sh
 CFLAGS="$SLKCFLAGS" \
 CXXFLAGS="$SLKCFLAGS" \
 ./configure \
   --prefix=/usr \
   --libdir=/usr/lib${LIBDIRSUFFIX} \
   --docdir=/usr/doc/$PRGNAM-$VERSION \
+  --infodir=/usr/info \
   --build=$ARCH-slackware-linux
 
 make
 make install DESTDIR=$PKG
 
-find $PKG | xargs file | grep -e "executable" -e "shared object" | grep ELF \
+find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
   | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
+
+rm -f $PKG/usr/info/dir
+gzip -9 $PKG/usr/info/*.info*
 
 mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
 cp -a \
-  AUTHORS COPYING ChangeLog INSTALL NEWS README TODO \
+  AUTHORS COPYING NEWS README \
   $PKG/usr/doc/$PRGNAM-$VERSION
 cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
 
